### ISSUE TITLE
Class Editor - promoted classes exclude start MP from running spell charge totals

### ISSUE THREAD

**Issue by ffhacksterex** [ffhacksterex/FFHacksterEx#118] opened 2022-09-12 07:34 UTC
If using 12 classes, the running totals for spell charges won't include the starting charges.
So if an extended class is added to the Starting MP range, and no spell are gained on level 2, then it works in-game and shows
2/0/0/0 0/0/0/0,
but in the Classes editor level 2 shows as
0/0/0/0 0/0/0/0.

**Comment by essellejaye** [comment] 2022-10-03 09:18
@ffhacksterex  Not able to reproduce this on a clean FF1 ROM.
Whether or not the Party Setup class count is set to 12, I still get the 2 starting MP charges even if I add all of the extended classes to the MP range, so level 2 shows as 3/1/0/0 0/0/0/0.

Also, since the base and extended classes share data, including the base classes (e.g. the mages).
FFH uses **`cur_class % 6`** when assigning starting MP, which means the base and extended class will both get it; since FFHEx didn't change this behavior, it follows suit.

Closing this, reopen if you spot the issue again.

**Closed by essellejaye** 2022-10-03 09:18 UTC
Labels: bug, next release
